[theme]
foreground = [0, 0, 0]
background = [0, 0, 0]
math_operators = [0, 0, 0]
keywords = [0, 0, 0]
outline = [0, 0, 0]
numbers = [0, 0, 0]
string_Literals = [0, 0, 0]
comments = [0, 0, 0]

[plugins]
# Simple config for plugins
example = true
